services:
  - type: web
    name: crm-backend
    runtime: docker
    plan: free
    branch: main
    rootDir: backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: MONGO_URI
        sync: false
      - key: CLIENT_ORIGIN
        sync: false

staticSites:
  - name: crm-frontend
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
